### DISCUSSION TITLE
Need help with finetuning on multiple datasets

### DISCUSSION THREAD

**Discussion by tcsmaster** [SalesforceAIResearch/uni2ts#201] [Q&A]
Hi!
I am using the same validation config yaml file as #193
```
_target_: uni2ts.data.builder.ConcatDatasetBuilder
_args_:
  - _target_: uni2ts.data.builder.simple.SimpleEvalDatasetBuilder
    dataset: building1_eval
    offset: -12790
    prediction_length: 96
    context_length: 1000
    patch_size: 64
    windows: 7920
    distance: 1
  - _target_: uni2ts.data.builder.simple.SimpleEvalDatasetBuilder
    dataset: building2_eval
    offset: -12790
    prediction_length: 96
    context_length: 1000
    patch_size: 64
    windows: 7920
    distance: 1
```
The parameters are not exactly the same, but they are appropraite for my datasets.
However I get an error when I call cli.eval (I have created the appropriate datasets and want to evaluate a fine-tuned model):
```
Traceback(most recent call last):
    File "uni2ts/cli/eval.py", line 30, in main:
        test_data, metadata = call(cgf.data)
TypeError: cannot unpack non-iterable ConcatDatasetBuilder object
```
My question would be:
- should I use `generate_eval_builders` instead?

Thanks in advance
