### ISSUE TITLE
Trying to finetune on a dataset

### ISSUE THREAD

**Issue by marcopeix** [SalesforceAIResearch/uni2ts#174]
- Working in Google Colab
- Using the latest version and cloned the repo inside Colab

I managed to prepare the data. I manually split my dataset into a train/val set and saved the dataset using HF in the `data` directory` at the root of the repo like this:

```python
url = "https://raw.githubusercontent.com/marcopeix/TimeSeriesForecastingUsingFoundationModels/refs/heads/main/data/walmart_sales_small.csv"
df = pd.read_csv(url, index_col='Date', parse_dates=True)
df = df[df['Store'] == 1]
finetune_df = df[:-32]
train_df, val_df = finetune_df[:-16], finetune_df[-16:]

def multivar_gen_func(df) -> Generator[dict[str, Any], None, None]:
    features_df = df.drop(['Store', 'Weekly_Sales'], axis=1)
    yield {
        "target": df['Weekly_Sales'].to_numpy(),
        "features": features_df.to_numpy().T,
        "start": df.index[0],
        "freq": pd.infer_freq(df.index),
        "item_id": "1",
    }
features = Features(
    dict(
        target=Sequence(Value("float32")),  
        features=Sequence(
            Sequence(Value("float32")), 
            length=len(df.columns) - 2  
        ),
        start=Value("timestamp[s]"),
        freq=Value("string"),
        item_id=Value("string"),
    )
)
hf_train_ds = datasets.Dataset.from_generator(
    lambda: multivar_gen_func(train_df), 
    features=features
)
hf_val_ds = datasets.Dataset.from_generator(
    lambda: multivar_gen_func(train_df),  # Pass df to the generator function
    features=features
)
hf_train_ds.save_to_disk("/content/uni2ts/data/store_ds")
hf_val_ds.save_to_disk("/content/uni2ts//data/store_ds_eval")
```

Then, I created a YAML configuration file for both training and validation. They are respectively in `/content/uni2ts/cli/conf/finetune/data/store_finetune.yaml` and `/content/uni2ts/cli/conf/finetune/val_data/store_finetune.yaml`.

The training YAML file is:
```
_target_: uni2ts.data.builder.simple.SimpleDatasetBuilder
dataset: store_ds
weight: 1000
storage_path: /content/uni2ts/data
```
and the validation YAML file is:
```
_target_: uni2ts.data.builder.ConcatDatasetBuilder
_args_:
  _target_: uni2ts.data.builder.simple.generate_eval_builders
  dataset: store_ds_eval
  offset: 95
  eval_length: 8
  prediction_lengths: [8]
  context_lengths: [16]
  patch_sizes: [16]
```
Then, I run the training command as specified:
```bash
python -m cli.train \
  -cp conf/finetune \
  run_name=store_sales_finetune \
  model=moirai_1.0_R_small \
  data=store_finetune \
  val_data=store_finetune
```

And it throws this error:
```
Error executing job with overrides: ['run_name=store_sales_finetune', 'model=moirai_1.0_R_small', 'data=store_finetune', 'val_data=store_finetune']
Error in call to target 'uni2ts.data.builder.simple.SimpleDatasetBuilder':
TypeError('expected str, bytes or os.PathLike object, not NoneType')
full_key: data
```

**My questions:**

1. What am I missing to fix this error?
2. How can I specify the maximum number of training steps?
3. What is the `offset` parameter in the validation YAML file?

Thanks in advance for your help!

**Comment by chenghaoliu89** [comment]
Hi @marcopeix 
1. Have you add your datapath into .env file? You can check the readme file for fine tuning guideline `echo "CUSTOM_DATA_PATH=PATH_TO_SAVE" >> .env`
2. you can add the argument in your cmd or directly modify it from `conf/finetune/default.yaml` file by setting `trainer.max_epochs`
3. date_offset (datetime string) or offset (integer) options determines the last time step of the fine-tuning train set. The validation set will be saved as DATASET_NAME_eval.

**Comment by marcopeix** [comment]
Yes, I specified the `CUSTOM_DATA_PATH` in an `.env` file at the root of the repository. When I do `!cat .env`, I get `CUSTOM_DATA_PATH="/content/uni2ts/data"`, but I still get the error.

**Comment by marcopeix** [comment]
Hi @chenghaoliu89, I got it working by using `os.environ` instead of loading the .env file.

One last question: what is the `weight` parameter in the training YAML file? What does the value 1000 stand for and what happens if we change it?

**Comment by chenghaoliu89** [comment]
Hi @marcopeix you can refer to this example https://github.com/SalesforceAIResearch/uni2ts/blob/main/example/lotsa_v1_weighting.ipynb, which explain dataset sample weight design. Fine-tuning config file follows the same idea

**Comment by AlexCohenDambros** [comment]
Hello @chenghaoliu89 and @marcopeix,

I was facing the same issue discussed here, and based on the previous suggestions, I was able to fine-tune the model on my dataset. However, I still have a question: how do I load the model after fine-tuning to make new predictions?

**Comment by AlexCohenDambros** [comment]
Hi @marcopeix and @chenghaoliu89,

I am also trying to do fine-tuning and encountered the same issues as mentioned in the thread. I followed the steps outlined here, replicating the code presented by @marcopeix, with the only change being the location where the data will be saved:

```python
hf_train_ds.save_to_disk("test_database/store_ds")
hf_val_ds.save_to_disk("test_database/store_ds_eval")
```

I followed the same approach and created two YAML configuration files for training and validation. They are located respectively at `cli/conf/finetune/data/data_fine_tuning.yaml` and `cli/conf/finetune/val_data/val_fine_tuning.yaml`.

The training YAML file is:

```yaml
_target_: uni2ts.data.builder.simple.SimpleDatasetBuilder
dataset: store_ds
storage_path: test_database
weight: 1000
```

And the validation YAML file is:

```yaml
_target_: uni2ts.data.builder.ConcatDatasetBuilder
_args_:
  _target_: uni2ts.data.builder.simple.generate_eval_builders
  dataset: store_ds_eval
  storage_path: test_database
  offset: 95
  eval_length: 8
  prediction_lengths: [8]
  context_lengths: [16]
  patch_sizes: [16]
```

Then, I ran the training command as specified, changing only the file name:

```bash
python -m cli.train -cp conf/finetune run_name=fine_tuning_morai model=moirai_1.0_R_small data=data_fine_tuning val_data=val_fine_tuning
```

However, it generates the following error:

```
AssertionError: Caught AssertionError in DataLoader worker process 0.
Original Traceback (most recent call last):
...
assert time >= b > a >= 0
AssertionError
```

Another question is: Is it possible to perform fine-tuning of the model without passing validation data?

Thank you in advance for your help!
