### ISSUE TITLE
Trying to finetune

### ISSUE THREAD

**Issue by AlexCohenDambros** [SalesforceAIResearch/uni2ts#195]
I am also trying to do fine-tuning and encountered the same issues as mentioned in #174. I followed the steps outlined, replicating the code presented in #174, with the only change being the location where the data will be saved:

```python
hf_train_ds.save_to_disk("test_database/store_ds")
hf_val_ds.save_to_disk("test_database/store_ds_eval")
```

I followed the same approach and created two YAML configuration files for training and validation. They are located respectively at `cli/conf/finetune/data/data_fine_tuning.yaml` and `cli/conf/finetune/val_data/val_fine_tuning.yaml`.

The training YAML file is:

```yaml
_target_: uni2ts.data.builder.simple.SimpleDatasetBuilder
dataset: store_ds
storage_path: test_database
weight: 1000
```

And the validation YAML file is:

```yaml
_target_: uni2ts.data.builder.ConcatDatasetBuilder
_args_:
  _target_: uni2ts.data.builder.simple.generate_eval_builders
  dataset: store_ds_eval
  storage_path: test_database
  offset: 95
  eval_length: 8
  prediction_lengths: [8]
  context_lengths: [16]
  patch_sizes: [16]
```

Then, I ran the training command as specified, changing only the file name:

```bash
python -m cli.train -cp conf/finetune run_name=fine_tuning_morai model=moirai_1.0_R_small data=data_fine_tuning val_data=val_fine_tuning
```

However, it generates the following error:

```
AssertionError: Caught AssertionError in DataLoader worker process 0.
Original Traceback (most recent call last):
...
assert time >= b > a >= 0
AssertionError
```

My questions:
1. Is it possible to perform fine-tuning of the model without passing validation data?
2. After performing the fine-tuning of the model, how do I load the model?

Thank you in advance for your help!
