### ISSUE TITLE
Questions about Finetuning LSF tasks

### ISSUE THREAD

**Issue by zqiao11** [SalesforceAIResearch/uni2ts#31]
Hi. I'm working on enhancing long sequence forecasting performance through finetuning. I have successfully replicated the zero-shot learning results shown in Table 22 and will use them as a baseline for comparison.

For a fair comparison, I need to do finetuning under the same train-val-test setup as the zero-shot experiments in Table 22. However, I am unsure if my approach is accurate. Below is a summary of my workflow to finetune Moirai-small on ETTh1 and evaluate it with prediction length of 96:

1. Following the lsf setup, I split the training data with the same offset as [here](https://github.com/SalesforceAIResearch/uni2ts/blob/main/src/uni2ts/eval_util/_lsf_dataset.py#L82):

```
python -m uni2ts.data.builder.simple ETTh1 dataset/ETT-small/ETTh1.csv --offset 8640
```

2. Accordingly, I revised the `conf/finetune/val_data/etth1.yaml` as

```
_target_: uni2ts.data.builder.ConcatDatasetBuilder
_args_:
  _target_: uni2ts.data.builder.simple.generate_eval_builders
  dataset: ETTh1_eval
  offset: 8640  # Same as _lsf_dataset.py
  eval_length: 2880  # Same as _lsf_dataset.py
  prediction_lengths: [96, 192, 336, 720]
  context_lengths: [1000, 2000, 3000, 4000, 5000]
  patch_sizes: [32, 64]
```

3. Then I finetuned a Moirai model with the same command as the example:
```
python -m cli.finetune \
  run_name=my_lsf_run \
  model=moirai_1.0_R_small \
  data=etth1 \
  val_data=etth1
```

4. Finally, I changed the ckpt in the model's yaml and evaluated the finetuned model by the 2nd approach in the example:
```
python -m cli.eval \
  run_name=my_lsf_run \
  model=moirai_1.0_R_small \
  model.patch_size=64 \
  model.context_length=5000 \
  data=lsf_test \
  data.dataset_name=ETTh1 \
  data.mode=M \
  data.prediction_length=96
```

Despite following these steps, the finetuning results are underperforming compared to the zero-shot outcomes (MSE is 0.375 and MAE is 0.402 in the original results).
![image](https://github.com/SalesforceAIResearch/uni2ts/assets/99472524/8a55c8b5-930d-4390-ae80-86e2f00e91b1)

I have a few questions:
1. Is the workflow above correct? Does it use the same train-val-test split setup of the original experiments? 
2. Given `data.mode = M` during testing, do I need to build the dataset with `wide_multivariate` for finetuning?  
3. If the workflow is correct, do you have any suggestions to improve the finetuning performance? 

Thank you for your assistance.
