### ISSUE TITLE
Loading checkpoints from local files

### ISSUE THREAD

**Issue by liu-jc** [SalesforceAIResearch/uni2ts#76]
**Is your feature request related to a problem? Please describe.**
We faced a problem when try to load the checkpoints from local files. Say using a model yaml under `eval` folder like following: 
```
_target_: uni2ts.model.moirai.MoiraiForecast
module:
  _target_: uni2ts.model.moirai.MoiraiModule.from_pretrained
  pretrained_model_name_or_path: /export/exp-series/Projects/uni2ts/outputs/pretrain/moirai_small/lotsa_v1_weighted/moirai_small
num_samples: 100
patch_size: ???
context_length: ???
```
It leads to the errors:
```
hydra.errors.InstantiationException: Error in call to target 'huggingface_hub.hub_mixin.ModelHubMixin.from_pretrained':
TypeError("MoiraiModule.__init__() missing 7 required positional arguments: 'distr_output', 'd_model', 'num_layers', 'patch_sizes', 'max_seq_len', 'attn_dropout_p', and 'dropout_p'")
full_key: model.module
```
I think the reason is that we don't have the config information in the checkpoint folder like huggingface did in [save_pretrained](https://huggingface.co/docs/transformers/v4.41.3/en/main_classes/model#transformers.PreTrainedModel.save_pretrained). Then we can only use `MoiraiForecast.load_from_checkpoint` which does not that fit into our current yaml file. 

**Describe the solution you'd like**
I think a way to fix this is to change/add a way to save checkpoints like huggingface did which save the config information. 

cc: @gorold @cuthalionn
